apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti
  template:
    metadata:
      labels:
        app: olivetti
    spec:
      containers:
      - name: app
        image: anbukarthika/olivetti-mlops:latest
        ports:
        - containerPort: 5000
